if: branch = master
language: perl
perl:
- '5.28.1'
install:
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | cpan
  - cpan install HTTP::Request::Common
  - cpan install JSON::Parse
script: perl test.pl
after_success:
  - ./cpan.sh
  - ./email.sh
notifications:
  slack:
    secure: bbhOYfEPmhx2+7aUWiZiVdqkqR+bmapkYaSBbnmNzkcdptZX9iUsf5ainoWQ9MjQa7IIw3rRZH4XIxBDLRp77BXf/ubOPnMiiT9yGmGa/Xt4fmRJ3umHY0LY1mGtzJ+gyzSVrHcEA1HbZyQ7r+v+9RTFmSrxgtIsPplCqYk6QfR7vG43rtmtyqU2led4tTFbrfDpUce5/iYUt94vZ1VYyHOtALQ0d8M2aeuz4TuoNn33vh5mAlwp800DccwoQeu15gir0ohQU1saHBCX4wMfuJevu2sOSS8Ds0rio2Q0rFtr4In6SapNqAF1M5C/aROIaO7Xe/o4dZAk9zkjI47eprNxCIX91ip9EOQF2ZV9SuMszHTreXh5Onz8/msyoWcmQK5RtU0Lj/klyI9b8Z8NIo7XKMEBnfGeJ/SCeYJrLWjNoNwm72j2RtRTNFTdMzgH42i08vqdjSX0qhPTvtZMAJiJJM2uRPsybwP0ybtFaW2NOqHLdR+abwhwD+3bKxKtckUwqq4ibBo7GbTpujVuCbR2MolGnJAqX5vQDbk2ZtI3jByi4FYYsdX7XX113jYyuTwbCe5tEOtAY0HDQhuAZy0vnPJDMHOP05hdE4lwhbG5eOaEGyHSKJdcePEc721yMgbYJfzKmlYolhzPjJVwtWpr8GkqfvWm6K/XgKXOxG0=
  email:
    on_success: never
    on_failure: never
